FROM python:3.11-slim

WORKDIR /app

# Instala dependências
RUN pip install --no-cache-dir streamlit plotly requests

# Copia frontend
COPY frontend/ frontend/

# Expõe porta
EXPOSE 8501

# Comando de início
CMD ["streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.headless=true"]
